import './globals.css';
import { Inter, Nunito } from 'next/font/google';
import Header from 'src/app/components/Header';
import Footer from 'src/app/components/Footer';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });
const nunito = Nunito({ subsets: ['latin'] });

export const metadata = {
	title: 'Blog',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={nunito.className}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
